import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[shell]
program = "/bin/zsh"

[window]
padding = { x = 10, y = 10 }
# decorations = "None"
opacity = 1.0

[font]
size = 14.0

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
